server:
  port: 8080

spring:
  # 环境
  profiles:
    include: config
  # datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${zkoj.database.url}
    username: ${zkoj.database.username}
    password: ${zkoj.database.password}
    type: com.alibaba.druid.pool.DruidDataSource
  # json
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null  # 当字段为null时不显示
  # activemq
  activemq:
    broker-url: ${zkoj.activemq.url} # activemq tcp监听地址
    user: ${zkoj.activemq.user}
    password: ${zkoj.activemq.password}
    in-memory: false
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: indi.snowmeow.zkojweb.model,indi.snowmeow.zkojweb.po

path: classpath:/

#logging:
#  level:
#    indi:
#      snowmeow:
#        zkojweb:
#          mapper: debug
#          controller: debug
