path: classpath:/
logging:
  level:
    indi:
      snowmeow:
        zkoj:
          base:
            dao: debug

spring:
  cloud:
    stream:
      bindings:
        SOLUTION_REQUEST_INPUT:
          destination: SOLUTION_REQUEST_TOPIC
          content-type: application/json

      rocketmq:
        binder:
          name-server: 192.168.31.179:9876
        bindings:
          SOLUTION_REQUEST_INPUT:
            producer:
              group: solution_request_producer
              sync: true

